### ISSUE TITLE
clicked on a place on a card  and got an unhandled exception

### ISSUE THREAD

**Issue by brinycoolie** [cdhorn/CardView#139]
3519: ERROR: grampsapp.py: line 173: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gramps/gui/grampsgui.py", line 794, in do_activate
    Gramps(self.argparser, self)
  File "/usr/lib/python3/dist-packages/gramps/gui/grampsgui.py", line 642, in __init__
    self._vm.open_activate(filename)
  File "/usr/lib/python3/dist-packages/gramps/cli/grampscli.py", line 249, in open_activate
    self._read_recent_file(path, username, password)
  File "/usr/lib/python3/dist-packages/gramps/cli/grampscli.py", line 288, in _read_recent_file
    self._post_load_newdb(filename, 'x-directory/normal', title)
  File "/usr/lib/python3/dist-packages/gramps/gui/viewmanager.py", line 1006, in _post_load_newdb
    self._post_load_newdb_gui(filename, filetype, title)
  File "/usr/lib/python3/dist-packages/gramps/gui/viewmanager.py", line 1046, in _post_load_newdb_gui
    self.__change_page(self.notebook.get_current_page())
  File "/usr/lib/python3/dist-packages/gramps/gui/viewmanager.py", line 885, in __change_page
    self.active_page.set_active()
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/card_view.py", line 513, in set_active
    ExtendedNavigationView.set_active(self)
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/extended_navigation.py", line 243, in set_active
    PageView.set_active(self)
  File "/usr/lib/python3/dist-packages/gramps/gui/views/pageview.py", line 338, in set_active
    self.build_tree()
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/card_view.py", line 393, in build_tree
    self.change_object(active_object)
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/card_view.py", line 443, in change_object
    self._render_page(page_context)
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/card_view.py", line 455, in _render_page
    view = view_builder(self.grstate, page_context)
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/view/views/view_builder.py", line 91, in view_builder
    return view(grstate, grcontext)
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/view/views/view_base.py", line 80, in __init__
    self.render_view()
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/view/views/view_base.py", line 86, in render_view
    self.build_view()
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/view/views/view_generic.py", line 77, in build_view
    self.view_body = self.build_object_groups(groups)
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/view/views/view_base.py", line 169, in build_object_groups
    object_groups = self.get_object_groups(
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/view/views/view_base.py", line 184, in get_object_groups
    {key: group_builder(self.grstate, key, obj, args)}
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/view/groups/group_builder.py", line 61, in group_builder
    group = build_simple_group(grstate, group_type, obj, args)
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/view/groups/group_builder.py", line 101, in build_simple_group
    group = framegroup(grstate, groptions, obj)
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/view/groups/group_places.py", line 66, in __init__
    profile = PlaceRefFrame(
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/view/frames/frame_place_ref.py", line 63, in __init__
    PlaceFrame.__init__(
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/view/frames/frame_place.py", line 69, in __init__
    self.__add_place_alternative_names(place)
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/view/frames/frame_place.py", line 148, in __add_place_alternative_names
    self.add_fact(
  File "/home/brian/.gramps/gramps51/plugins/CardView/src/view/frames/frame_primary.py", line 181, in add_fact
    self.widgets["extra"].add_fact(fact, label=label)
KeyError: 'extra'

**Comment by cdhorn** [comment]
Thank you for reporting this bug!  I think ba5d71dcddd35ef40bab3cd5ac8e476483a448d9 which I just pushed should address it. Please let me know if you are able to reproduce. Thanks!
