### ISSUE TITLE
Few more errors only one of which I can recreate!:  ValueError: invalid tree path '4'

### ISSUE THREAD

**Issue by wroldwiedbwe** [cdhorn/CardView#140]
- [ ] don't load any family tree just close the FTM ( family tree manager )
 Select "Tags" category 
 Select "Configure the active view"
 Press "Apply"
 
 gives the following error: 

51496: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "Z:\PortableApps\GrampsPortable\App\Gramps\gramps\gui\columnorder.py", line 174, in __on_apply
    node = self.model.get_iter((int(i), ))
  File "AIO/gi/overrides/Gtk.py", line 839, in get_iter
ValueError: invalid tree path '4'

----------------------------

 - [ ] Bonus happened once switching between the CardView's and not sure how to replicate sorry, possibly happened switching between family trees, I'll keep watching for this one!:

186123: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "Z:\PortableApps\GrampsPortable\App\Gramps\gramps\gui\navigator.py", line 274, in cb_view_clicked
    self.viewmanager.goto_page(int(cat_num), int(view_num))
  File "Z:\PortableApps\GrampsPortable\App\Gramps\gramps\gui\viewmanager.py", line 786, in goto_page
    self.__create_page(page_def[0], page_def[1])
  File "Z:\PortableApps\GrampsPortable\App\Gramps\gramps\gui\viewmanager.py", line 840, in __create_page
    self.active_page.post_create()
AttributeError: 'NoneType' object has no attribute 'post_create'

**Comment by cdhorn** [comment]
For the post_create issue I opened a Mantis item here: https://gramps-project.org/bugs/view.php?id=12638

The first issue fixed in a0cc951cbd499d51ebcf16d3322ac74280d4d435
