### ISSUE TITLE
TypeError while trying to move from People to Event

### ISSUE THREAD

**Issue by patlx** [cdhorn/CardView#141]
When clicking on an event in People view CV don't move from one view to another but log displays this error:

Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gen\utils\callback.py", line 405, in emit
    fn(*args)
  File "C:\Users\1\AppData\Roaming\gramps\gramps51\plugins\CardView\src\extended_navigation.py", line 288, in goto_active
    return self.change_category(current_handle[0])
  File "C:\Users\1\AppData\Roaming\gramps\gramps51\plugins\CardView\src\extended_navigation.py", line 215, in change_category
    primary_category
TypeError: list indices must be integers or slices, not NoneType

---

On GrampsAIO64-5.1.3-2, Win 10

**Comment by patlx** [comment]
Same issue and same error message when trying to move from People to Family view

**Comment by cdhorn** [comment]
Thanks for reporting this as well.

**Comment by cdhorn** [comment]
Closing, tracking as part of #142
