### ISSUE TITLE
Sorting tags by Priority

### ISSUE THREAD

**Issue by patlx** [cdhorn/CardView#144]
I've tried to sort tags in the first of two tags views using Priority as sort key and I've got this;

91505: ERROR: grampsapp.py: line 157: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gui\views\listview.py", line 657, in column_clicked
    search=filter_info, sort_map=self.column_order())
  File "C:\Users\1\AppData\Roaming\gramps\gramps51\plugins\CardView\src\tagview.py", line 107, in __init__
    sort_map=sort_map,
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gui\views\treemodels\flatbasemodel.py", line 486, in __init__
    self.rebuild_data()
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gui\views\treemodels\flatbasemodel.py", line 613, in _rebuild_filter
    allkeys = self.sort_keys()
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gui\views\treemodels\flatbasemodel.py", line 570, in sort_keys
    for key, data in cursor]
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gui\views\treemodels\flatbasemodel.py", line 570, in <listcomp>
    for key, data in cursor]
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gui\views\treemodels\flatbasemodel.py", line 476, in <lambda>
    self.sort_func = lambda x: glocale.sort_key(self.smap[col](x))
  File "C:\Program Files\GrampsAIO64-5.1.3\gramps\gen\utils\grampslocale.py", line 926, in sort_key
    return hexlify(self.collator.getCollationKey(string).getByteArray()).decode()
icu.InvalidArgsError: (<class 'icu.RuleBasedCollator'>, 'getCollationKey', (63,))

Name and Color have sorted well.

**Comment by cdhorn** [comment]
The list view logic appears to expect strings, not numbers.  The quick fix is to make them 0 padded strings so they sort properly.
