### ISSUE TITLE
Deleting Template error

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#156]
This may be redundant as I have not yet downloaded since 2 days ago.

Had copied a template for the Tag cardview, modified it, and applied it.
Left Gramps idle then returned several hours later to delete it before downloading the newest revision.
Clicking the "Remove Template" button gave the following error and left the remaining "Minimal" and "default" templates unselected"

```
2882146: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\CardView\src\view\config\config_templates.py", line 423, in cb_delete_clicked
    self.remove_template(name, delete=True)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\CardView\src\view\config\config_templates.py", line 441, in remove_template
    self._load_layout()
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\CardView\src\view\config\config_templates.py", line 209, in _load_layout
    self._select_active()
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\CardView\src\view\config\config_templates.py", line 228, in _select_active
    selection.select_iter(iter_)
TypeError: Argument 1 does not allow None as a value

```

**Comment by cdhorn** [comment]
I believe this is fixed from last refactor, so closing.
