### ISSUE TITLE
Tag view: unhandled exception on QuickView context menu items 

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#169]
When a Tag is selected in on of the Tags view modes, there are 2 QuickView submenu options in the Context menu: "Link References" & "Note References". Both give an error:

```
[5569997: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gui\plug\quick\_quickreports.py", line 172, in <lambda>
    track=track)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gui\plug\quick\_quickreports.py", line 281, in run_report
    obj = dbstate.db.get_note_from_handle(handle)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gen\db\generic.py", line 1294, in get_note_from_handle
    return self._get_from_handle(NOTE_KEY, Note, handle)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gen\db\generic.py", line 1270, in _get_from_handle
    raise HandleError('Handle %s not found' % handle)
gramps.gen.errors.HandleError: Handle f0aa931408cd974b08c7466a08 not found
](url)
```

**Comment by cdhorn** [comment]
Yes think I mentioned this before when I added it. They are not applicable, but removing them from the menu triggers a bug in some underlying Gramps core code somewhere.

I need to add some kind of a "Known Issues" section.
