### ISSUE TITLE
Unexpected error switching to view with Empty Tree

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#187]
Gramps was running slow with my large tree.  So I loaded an Empty tree (so that configuring the Sidebars and view would have a faster re-population of the view) before restarting Gramps. When navigating from Relationships default view to the People Person CardView, the following error occurred :

```
132067537: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gui\viewmanager.py", line 895, in page_changer
    self.active_page.change_page()
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\CardView\src\card_view.py", line 379, in change_page
    self._set_status_bar(self.current_context)
  File "C:\Users\DistrictSupport\AppData\Roaming\gramps\gramps51\plugins\CardView\src\card_view.py", line 493, in _set_status_bar
    page_context.primary_obj.obj.get_handle(),
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gen\utils\db.py", line 328, in navigation_label
    obj = db.get_person_from_handle(handle)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gen\db\generic.py", line 1282, in get_person_from_handle
    return self._get_from_handle(PERSON_KEY, Person, handle)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gen\db\generic.py", line 1270, in _get_from_handle
    raise HandleError('Handle %s not found' % handle)
gramps.gen.errors.HandleError: Handle d24aa5b66d94b7306c401e73ab6 not found
```

**Comment by cdhorn** [comment]
I wasn't fully clearing state on a db switch. This should be fixed with 05e79567145339f088055f93638993d662a647c4 as well as another similar issue.
