### ISSUE TITLE
Person Card config layout options errors using version "0.99.100

### ISSUE THREAD

**Issue by PQYPLZXHGF** [cdhorn/CardView#198]
Select the person card and edit the layout for person  apart from the first item (tabbed mode) check and select all the other items and then applied gives:

219377: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\config\config_layout.py", line 223, in apply_changes
    self.grstate.reload_config(refresh_only=False, defer_refresh=False)
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\common\common_classes.py", line 636, in reload_config
    refresh_only=refresh_only, defer_refresh=defer_refresh
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\card_view.py", line 251, in reload_config
    self._perform_config_refresh()
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\card_view.py", line 298, in _perform_config_refresh
    self.build_tree()
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\card_view.py", line 396, in build_tree
    self.change_object(active_object)
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\card_view.py", line 455, in change_object
    self._render_page(page_context)
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\card_view.py", line 466, in _render_page
    view = view_builder(self.grstate, page_context)
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\views\view_builder.py", line 94, in view_builder
    return view(grstate, grcontext)
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\views\view_person.py", line 46, in __init__
    GrampsObjectView.__init__(self, grstate, grcontext)
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\views\view_base.py", line 80, in __init__
    self.render_view()
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\views\view_base.py", line 86, in render_view
    self.build_view()
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\views\view_person.py", line 70, in build_view
    self.grcontext.primary_obj, age_base=age_base
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\views\view_base.py", line 173, in build_object_groups
    space, groups, gramps_obj.obj, age_base=age_base
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\views\view_base.py", line 188, in get_object_groups
    {group: group_builder(self.grstate, group, obj, args)}
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\groups\group_builder.py", line 63, in group_builder
    group = build_simple_group(grstate, group_type, obj, args)
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\groups\group_builder.py", line 106, in build_simple_group
    group = cardgroup(grstate, groptions, obj)
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\groups\group_names.py", line 53, in __init__
    obj.primary_name,
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\cards\card_name.py", line 59, in __init__
    self.__add_name_origin_surnames(name)
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\cards\card_name.py", line 120, in __add_name_origin_surnames
    origin_type = get_origin_type(surname)
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\cards\card_name.py", line 185, in get_origin_type
    origin_type = MISSING_ORIGIN
NameError: name 'MISSING_ORIGIN' is not defined

--------
Then after above attempting to reset cardview back to "Defaults" gives:

333107: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\config\config_utils.py", line 177, in reset_option_space
    options = self.get_option_space()
  File "C:\PortableApps\GrampsPortable\Data\settings\gramps\gramps51\plugins\CardView-master\src\view\config\config_utils.py", line 196, in get_option_space
    settings = self.config.get_section_settings("options")
  File "C:\PortableApps\GrampsPortable\App\Gramps\gramps\gen\utils\configmanager.py", line 246, in get_section_settings
    return list(self.data[section].keys())
KeyError: 'options'

**Comment by cdhorn** [comment]
Second issue half not examined yet.
