### ISSUE TITLE
Error when going to parent/sibling/Assosiation in active tab in settings.

### ISSUE THREAD

**Issue by TheMihle** [cdhorn/CardView#218]
Error when going to Parent/Sibling/Assosiation in active tab in settings.
Is those settings tab even supposed to be there, is it possible for a parent to be active and not just be the person?

**Error message:**

```
529955: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Users\Mihle\AppData\Roaming\gramps\gramps51\plugins\CardView\src\view\config\config_objects.py", line 105, in handle_page_switch
    page = render_page()
  File "C:\Users\Mihle\AppData\Roaming\gramps\gramps51\plugins\CardView\src\view\config\config_panel.py", line 145, in <lambda>
    configdialog, grstate, space, "parent"
  File "C:\Users\Mihle\AppData\Roaming\gramps\gramps51\plugins\CardView\src\view\config\config_objects.py", line 168, in build_person_grid
    "{}.{}.show-parents".format(space, person),
  File "C:\Users\Mihle\AppData\Roaming\gramps\gramps51\plugins\CardView\src\view\config\configure_dialog.py", line 283, in add_checkbox
    checkbox.set_active(config.get(constant))
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gen\utils\configmanager.py", line 382, in get
    (section, setting))
AttributeError: No such config setting name: 'active.parent.show-parents'
```

**Comment by cdhorn** [comment]
This should have been fixed with 831b6378ff28a09748a313b8e921578612605e7d
