### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by mixthumb** [cdhorn/CardView#233]
I had some crashes with CardView from time ot time, but today CardView was stuck in a loop of crashes and I manually needed to remove all traces before I could restart Gramps properly again. I liked wirking with CardView, but the crashes made continuing to use it impossible
Win10 22H2
Gramps AIO64-5.1.5-1

Errordetail:
5897: ERROR: grampsapp.py: line 174: Unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gui\grampsgui.py", line 794, in do_activate
    Gramps(self.argparser, self)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gui\grampsgui.py", line 642, in __init__
    self._vm.open_activate(filename)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\cli\grampscli.py", line 249, in open_activate
    self._read_recent_file(path, username, password)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\cli\grampscli.py", line 288, in _read_recent_file
    self._post_load_newdb(filename, 'x-directory/normal', title)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gui\viewmanager.py", line 1006, in _post_load_newdb
    self._post_load_newdb_gui(filename, filetype, title)
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gui\viewmanager.py", line 1046, in _post_load_newdb_gui
    self.__change_page(self.notebook.get_current_page())
  File "C:\Program Files\GrampsAIO64-5.1.5\gramps\gui\viewmanager.py", line 885, in __change_page
    self.active_page.set_active()
  File "C:\Users\ursus\AppData\Roaming\gramps\gramps51\plugins\CardView-master\src\card_view.py", line 531, in set_active
    GlobalNavigationView.set_active(self)
  File "C:\Users\ursus\AppData\Roaming\gramps\gramps51\plugins\CardView-master\src\global_navigation.py", line 271, in set_active
    self.goto_active(None)
  File "C:\Users\ursus\AppData\Roaming\gramps\gramps51\plugins\CardView-master\src\global_navigation.py", line 299, in goto_active
    self.change_person_category()
  File "C:\Users\ursus\AppData\Roaming\gramps\gramps51\plugins\CardView-master\src\global_navigation.py", line 244, in change_person_category
    self.change_category("Person")
  File "C:\Users\ursus\AppData\Roaming\gramps\gramps51\plugins\CardView-master\src\global_navigation.py", line 224, in change_category
    category_views = viewmanager.get_views()[category_index]
TypeError: list indices must be integers or slices, not NoneType

**Comment by cdhorn** [comment]
Interesting. I'm assuming this with current version? Are you able to reproduce that?

**Comment by mixthumb** [comment]
Yes it happened on current version and it was very consistent. Uninstalled
the package and rebooted, re-installed it and yep bingo it crashed again.

Op zo 12 feb. 2023 om 21:06 schreef Christopher Horn <
***@***.***>:

**Comment by cdhorn** [comment]
I did see this when figuring out the category switching approach but have not seen it in a long time and am unable to recreate it.  So I just pushed a fix so it will only attempt to switch if it gets back a valid index.  Not understanding the state of all your options, plugins, database not sure how helpful that will be though.

**Comment by cdhorn** [comment]
Did that safety check improve things any for you?

**Comment by emyoulation** [comment]
I had a problem a while back that was based a problem with the active object. I had to force Gramps to quit to get out of the error loop. But I had Gramps preferences set to auto-load the last tree and view.  So, (after breaking the lock) Gramps would re-enter the loop. It was necessary to clean the .ini files to not attempt to reload the View.

Maybe there could be something like a counter that is incremented (or a lock added) when initializing a CardView view mode and decremented (or deleted) on normal exit of the view mode. And have a fallback/bailout option if the lock already exists.

**Comment by cdhorn** [comment]
No further update from user so closing this.
